"use client";

import { usePathname } from "next/navigation";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "sds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const hideLayout = ["/login", "/signup", "/otp_verification"].includes(pathname);

  return (
    <html lang="en" className={hideLayout ? " w-full h-full" : ""}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${hideLayout ? " h-full flex items-center justify-center bg-gray-100" : ""}`}>
        {!hideLayout && <Navbar />}
        <div className={`flex ${hideLayout ? "h-screen w-screen" : ""}`}>
          {!hideLayout && <Sidebar />}
          <main className={`flex-1 p-6 ${hideLayout ? "flex items-center justify-center h-full" : ""}`}>{children}</main>
        </div>
      </body>
    </html>
  );
}
